[QoF] Adding feature that automatically rotate player view when find a item/tile entity successfully
GTNewHorizons/FindIt pull request #12
Opened 2024-02-12 05:18 UTC by gitboy14

2024-02-12 06:44 UTC, Caedis commented
Please have this be under a config option, default false

2024-02-12 06:46 UTC, Caedis requested changes

2024-02-12 06:46 UTC, Caedis commented on src/main/java/com/gtnh/findit/service/blockfinder/ClientBlockFindService.java
> +    public void lookAtTarget(EntityClientPlayerMP player, BlockFoundResponse response){
Consider moving this to a util class so its not duplicated between these this class and `ClientItemFindService`

2024-02-16 05:52 UTC, gitboy14 commented
> Please have this be under a config option, default false

Anything wrong?

2024-02-16 06:35 UTC, Caedis commented
The code itself looks fine to me, I just want some other devs to take a look

2024-02-16 17:16 UTC, slprime commented
Is it possible to make it always show in the center of the block, not around?

![Minecraft1 7 102024-02-1619-11-51](https://github.com/GTNewHorizons/FindIt/assets/31038811/120325c2-cd0d-4c90-a615-cff835f84fc9)

2024-02-17 07:37 UTC, slprime approved these changes

2024-02-17 08:00 UTC, Caedis approved these changes

2024-02-17 08:04 UTC, merged

2024-02-17 08:15 UTC, Dream-Master commented
I will change the config to true as default in gtnh otherwise no one will find this nice feature.

2024-02-17 08:19 UTC, Caedis commented
Was actually thinking about that too

2024-02-17 13:34 UTC, gitboy14 commented
> Is it possible to make it always show in the center of the block, not around?
> 
> ![Minecraft1 7 102024-02-1619-11-51](https://private-user-images.githubusercontent.com/31038811/305491515-120325c2-cd0d-4c90-a615-cff835f84fc9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDg2ODEsIm5iZiI6MTcwODE0ODM4MSwicGF0aCI6Ii8zMTAzODgxMS8zMDU0OTE1MTUtMTIwMzI1YzItY2QwZC00YzkwLWE2MTUtY2ZmODM1Zjg0ZmM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA1Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MTNiNTg2Zjc2NTEwNzg2MzlkNmFhNTlmYmU0NjQwOTgwYmI5YmIyZDM1ZmZiMzYwYjk0ZjA5ZDM1YWQ3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCie_7s8Y1kUD4OiG6FaOYep1StIMn9Y3SwRDEwXEPY) [ ![Minecraft1 7 102024-02-1619-11-51](https://private-user-images.githubusercontent.com/31038811/305491515-120325c2-cd0d-4c90-a615-cff835f84fc9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDg2ODEsIm5iZiI6MTcwODE0ODM4MSwicGF0aCI6Ii8zMTAzODgxMS8zMDU0OTE1MTUtMTIwMzI1YzItY2QwZC00YzkwLWE2MTUtY2ZmODM1Zjg0ZmM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA1Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MTNiNTg2Zjc2NTEwNzg2MzlkNmFhNTlmYmU0NjQwOTgwYmI5YmIyZDM1ZmZiMzYwYjk0ZjA5ZDM1YWQ3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCie_7s8Y1kUD4OiG6FaOYep1StIMn9Y3SwRDEwXEPY) ](https://private-user-images.githubusercontent.com/31038811/305491515-120325c2-cd0d-4c90-a615-cff835f84fc9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDg2ODEsIm5iZiI6MTcwODE0ODM4MSwicGF0aCI6Ii8zMTAzODgxMS8zMDU0OTE1MTUtMTIwMzI1YzItY2QwZC00YzkwLWE2MTUtY2ZmODM1Zjg0ZmM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA1Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MTNiNTg2Zjc2NTEwNzg2MzlkNmFhNTlmYmU0NjQwOTgwYmI5YmIyZDM1ZmZiMzYwYjk0ZjA5ZDM1YWQ3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCie_7s8Y1kUD4OiG6FaOYep1StIMn9Y3SwRDEwXEPY) [ ](https://private-user-images.githubusercontent.com/31038811/305491515-120325c2-cd0d-4c90-a615-cff835f84fc9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDg2ODEsIm5iZiI6MTcwODE0ODM4MSwicGF0aCI6Ii8zMTAzODgxMS8zMDU0OTE1MTUtMTIwMzI1YzItY2QwZC00YzkwLWE2MTUtY2ZmODM1Zjg0ZmM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA1Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MTNiNTg2Zjc2NTEwNzg2MzlkNmFhNTlmYmU0NjQwOTgwYmI5YmIyZDM1ZmZiMzYwYjk0ZjA5ZDM1YWQ3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCie_7s8Y1kUD4OiG6FaOYep1StIMn9Y3SwRDEwXEPY)

Sure, now it works fine.

2024-02-17 13:43 UTC, YannickMG commented
A bit late but as a suggestion, how about making it so subsequent presses of the keybind have you focus on the next find in range, letting you cycle through them?

2024-02-21 09:51 UTC, AnrDaemon commented
Also, if a rotation could not be instant, that'd also help.